import React, { useState, useCallback, useRef } from 'react';
import {
  View, Text, ScrollView, TextInput, TouchableOpacity,
  ActivityIndicator, StyleSheet, Image, Modal,
} from 'react-native';
import { COLORS, globalStyles } from '../theme';
import ForexSignalCard from '../components/ForexSignalCard';
import ChartWithZones from '../components/ChartWithZones';
import ChartView from '../components/ChartView';
import ConfirmTradeScreen from './ConfirmTradeScreen';

const TIMEFRAMES = ['1m', '5m', '15m', '1h', '4h', '1d'];

const ForexScreen = ({
  analyze, signal, loading, pair, setPair,
  uploading, pickImage, lastUploadedChart, IMAGE_BASE_URL,
}) => {
  const [mode, setMode] = useState('STRICT');         // STRICT | SCALP
  const [dataSource, setDataSource] = useState('YAHOO'); // YAHOO | REALTIME
  const [timeframe, setTimeframe] = useState('15m');
  const [showChart, setShowChart] = useState(false);
  const [showConfirmTrade, setShowConfirmTrade] = useState(false);
  const [chartViewMode, setChartViewMode] = useState('PRO'); // PRO | LITE
  const [balance, setBalance] = useState('1000');
  const [riskPct, setRiskPct] = useState('1');
  // chartSignal: generated by ChartWithZones internally (autoSignal)
  // This is the primary signal passed to ConfirmTradeScreen so the
  // TradeZonesChart stays perfectly in sync with what was drawn on screen.
  const [chartSignal, setChartSignal] = useState(null);
  const chartSignalPair = useRef(null);

  const onChartSignal = useCallback((sig) => {
    // Only accept if it matches the current pair to avoid stale updates
    if (sig?.pair?.toUpperCase() === pair?.toUpperCase()) {
      chartSignalPair.current = sig.pair;
      setChartSignal(sig);
    }
  }, [pair]);

  // Reset chartSignal when pair changes
  const handlePairChange = useCallback((p) => {
    setChartSignal(null);
    chartSignalPair.current = null;
    setPair(p);
  }, [setPair]);

  const onAnalyze = () => {
    analyze({
      pair,
      mode,
      dataSource,
      balance: parseFloat(balance) || 0,
      riskPct: parseFloat(riskPct) || 0,
    });
  };

  return (
    <ScrollView contentContainerStyle={styles.scrollContent}>
      {/* INPUT */}
      <View style={styles.searchSection}>
        <TextInput
          style={styles.input}
          placeholder="Enter Pair (GOLD, BTC, EURUSD)"
          placeholderTextColor="#444"
          value={pair}
          onChangeText={handlePairChange}
          autoCapitalize="characters"
        />

        {/* MODE TOGGLE */}
        <View style={styles.toggleContainer}>
          <TouchableOpacity
            style={[styles.toggleBtn, mode === 'STRICT' && styles.activeToggle]}
            onPress={() => setMode('STRICT')}
          >
            <Text style={styles.toggleText}>SWING</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.toggleBtn, mode === 'SCALP' && styles.activeToggle]}
            onPress={() => setMode('SCALP')}
          >
            <Text style={styles.toggleText}>SCALP ⚡</Text>
          </TouchableOpacity>
        </View>

        {/* DATA SOURCE */}
        <View style={styles.toggleContainer}>
          <TouchableOpacity
            style={[styles.toggleBtn, dataSource === 'YAHOO' && styles.activeToggle]}
            onPress={() => setDataSource('YAHOO')}
          >
            <Text style={styles.toggleText}>YAHOO</Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.toggleBtn, dataSource === 'REALTIME' && styles.activeToggle]}
            onPress={() => setDataSource('REALTIME')}
          >
            <Text style={styles.toggleText}>REALTIME ⚡</Text>
          </TouchableOpacity>
        </View>

        {/* RISK INPUTS */}
        <View style={styles.riskRow}>
          <View style={{ flex: 1, marginRight: 6 }}>
            <Text style={styles.smallLabel}>Balance ($)</Text>
            <TextInput
              style={styles.smallInput}
              keyboardType="numeric"
              value={balance}
              onChangeText={setBalance}
              placeholderTextColor="#444"
            />
          </View>
          <View style={{ flex: 1, marginLeft: 6 }}>
            <Text style={styles.smallLabel}>Risk %</Text>
            <TextInput
              style={styles.smallInput}
              keyboardType="numeric"
              value={riskPct}
              onChangeText={setRiskPct}
              placeholderTextColor="#444"
            />
          </View>
        </View>

        <TouchableOpacity style={styles.searchButton} onPress={onAnalyze}>
          <Text style={styles.searchButtonText}>Start Smart Analysis</Text>
        </TouchableOpacity>

        <View style={{ flexDirection: 'row', marginTop: 10 }}>
          <TouchableOpacity
            style={[styles.searchButton, { backgroundColor: '#1a1a1a', flex: 1, marginRight: 5 }]}
            onPress={() => setShowChart(s => !s)}
          >
            <Text style={styles.searchButtonText}>
              {showChart ? 'Hide SMC Chart' : 'Show SMC Chart 📊'}
            </Text>
          </TouchableOpacity>
          <TouchableOpacity
            style={[styles.searchButton, { backgroundColor: COLORS.primary, flex: 1, marginLeft: 5 }]}
            onPress={() => setShowConfirmTrade(true)}
          >
            <Text style={styles.searchButtonText}>TRADE CONFIRM</Text>
          </TouchableOpacity>
        </View>
      </View>

      {/* CHART + TIMEFRAME PICKER */}
      {showChart && (
        <View style={styles.chartWrap}>
          {/* Chart Mode Toggle */}
          <View style={[styles.toggleContainer, { marginBottom: 15 }]}>
            <TouchableOpacity
              style={[styles.toggleBtn, chartViewMode === 'PRO' && styles.activeToggle]}
              onPress={() => setChartViewMode('PRO')}
            >
              <Text style={styles.toggleText}>SMC PRO 🛡️</Text>
            </TouchableOpacity>
            <TouchableOpacity
              style={[styles.toggleBtn, chartViewMode === 'LITE' && styles.activeToggle]}
              onPress={() => setChartViewMode('LITE')}
            >
              <Text style={styles.toggleText}>LITE VIEW ⚡</Text>
            </TouchableOpacity>
          </View>

          {chartViewMode === 'LITE' ? (
            <>
              <View style={styles.tfRow}>
                {TIMEFRAMES.map(tf => (
                  <TouchableOpacity
                    key={tf}
                    style={[styles.tfBtn, timeframe === tf && styles.tfBtnActive]}
                    onPress={() => setTimeframe(tf)}
                  >
                    <Text style={styles.tfText}>{tf}</Text>
                  </TouchableOpacity>
                ))}
              </View>
              <ChartView pair={pair} timeframe={timeframe} dataSource={dataSource} signal={signal} />
            </>
          ) : (
            <ChartWithZones pair={pair} signal={signal} dataSource={dataSource} onSignal={onChartSignal} />
          )}
        </View>
      )}

      <TouchableOpacity
        style={styles.uploadBtn}
        onPress={pickImage}
        disabled={uploading}
      >
        <Text style={styles.uploadBtnText}>
          {uploading ? 'Processing...' : 'Audit Price Action Chart'}
        </Text>
      </TouchableOpacity>

      {/* RESULT */}
      {loading ? (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color={COLORS.primary} />
          <Text style={styles.loadingText}>Analyzing {pair.toUpperCase()}...</Text>
        </View>
      ) : (
        <View>
          {!signal && (
            <View style={styles.placeholder}>
              <Text style={styles.placeholderTitle}>TrendWay PRO</Text>
              <Text style={styles.placeholderSub}>
                AI Smart Money analysis for Forex, Gold & Crypto
              </Text>
            </View>
          )}

          {signal && <ForexSignalCard signal={signal} />}

          {lastUploadedChart && (
            <View style={styles.chartBox}>
              <Text style={styles.chartTitle}>SMC Audit: Liquidity & Zones</Text>
              <Image
                source={{ uri: IMAGE_BASE_URL + lastUploadedChart }}
                style={styles.fullImg}
                resizeMode="contain"
              />
            </View>
          )}
        </View>
      )}

      <Modal visible={showConfirmTrade} animationType="slide" onRequestClose={() => setShowConfirmTrade(false)}>
        <ConfirmTradeScreen
          onClose={() => setShowConfirmTrade(false)}
          signal={chartSignal ?? signal}
          pair={pair}
          dataSource={dataSource}
          signalSource={chartSignal ? 'CHART' : signal ? 'API' : null}
        />
      </Modal>
    </ScrollView>
  );
};

const styles = StyleSheet.create({
  scrollContent: { padding: 20 },
  searchSection: { marginBottom: 10 },
  input: {
    backgroundColor: '#111', color: '#FFF', padding: 18, borderRadius: 15,
    fontSize: 18, marginBottom: 12, borderWidth: 1, borderColor: '#222',
  },
  searchButton: {
    backgroundColor: COLORS.primary, padding: 18, borderRadius: 15, alignItems: 'center',
  },
  searchButtonText: { color: '#FFF', fontWeight: 'bold' },
  uploadBtn: {
    padding: 14, borderRadius: 12, alignItems: 'center',
    borderWidth: 1, borderColor: '#222', marginBottom: 20, marginTop: 12,
  },
  uploadBtnText: { color: '#666', fontSize: 14 },
  loadingContainer: { marginTop: 50, alignItems: 'center' },
  loadingText: { color: '#666', marginTop: 10 },
  chartBox: { marginTop: 10 },
  chartTitle: { color: '#FFF', fontSize: 16, fontWeight: 'bold', marginBottom: 10 },
  fullImg: { width: '100%', height: 300, borderRadius: 15, backgroundColor: '#111' },
  toggleContainer: { flexDirection: 'row', marginBottom: 12 },
  toggleBtn: {
    flex: 1, padding: 12, borderRadius: 10, backgroundColor: '#111',
    alignItems: 'center', marginHorizontal: 4, borderWidth: 1, borderColor: '#222',
  },
  activeToggle: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  toggleText: { color: '#FFF', fontWeight: 'bold', fontSize: 12 },
  riskRow: { flexDirection: 'row', marginBottom: 12 },
  smallLabel: { color: '#888', fontSize: 11, marginBottom: 4 },
  smallInput: {
    backgroundColor: '#111', color: '#FFF', padding: 12, borderRadius: 10,
    borderWidth: 1, borderColor: '#222', fontSize: 14,
  },
  chartWrap: { marginVertical: 12 },
  tfRow: { flexDirection: 'row', marginBottom: 8, flexWrap: 'wrap' },
  tfBtn: {
    paddingVertical: 6, paddingHorizontal: 12, borderRadius: 8,
    borderWidth: 1, borderColor: '#222', marginRight: 6, marginBottom: 6,
    backgroundColor: '#111',
  },
  tfBtnActive: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
  tfText: { color: '#FFF', fontSize: 11, fontWeight: 'bold' },
  placeholder: {
    backgroundColor: '#0f0f0f', borderRadius: 18, padding: 30,
    alignItems: 'center', borderWidth: 1, borderColor: '#1f1f1f',
  },
  placeholderTitle: { color: '#FFF', fontSize: 22, fontWeight: 'bold', marginBottom: 10 },
  placeholderSub: { color: '#666', textAlign: 'center', lineHeight: 22 },
});

export default ForexScreen;
